# Generated by Django 5.1.2 on 2024-11-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeflowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
