# Generated by Django 5.1.2 on 2024-11-11 23:08

from django.db import migrations
from django.utils.text import slugify

def populate_course_slugs(apps, schema_editor):
    # Get the Course model from the historical version of the app
    Course = apps.get_model('codeflowapp', 'Course')
    
    # Loop through all existing Course objects and set the slug
    for course in Course.objects.all():
        if not course.slug:  # Only update courses where the slug is not already set
            course.slug = slugify(course.title)  # Generate a slug from the course title
            course.save()  # Save the course with the generated slug

class Migration(migrations.Migration):

    dependencies = [
        ('codeflowapp', '0002_course_slug'),  # Make sure this is correct
    ]

    operations = [
        migrations.RunPython(populate_course_slugs),  # Run the function to populate slugs
    ]
