# Generated by Django 5.1.2 on 2024-11-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeflowapp', '0005_category_resource_resourcedownload_resourcerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
